### ISSUE TITLE
Watch window: sometimes I cannot expand/collapse variable info.

### ISSUE THREAD

**Issue by paprykarz** [joonty/vdebug#127]
Hi,

When I try to collapse info about _$_SERVER_ PHP superglobal, I get a message:

```
- [Debug] {pon 20 2014 00:40:43} User action in watch window, line 11

- [ERROR] {pon 20 2014 00:40:43} An error occured: <type 'exceptions.IndexError'>
Traceback (most recent call last):
  File "/home/paprykarz/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 87, in handle_return_keypress
    return self.event_dispatcher.by_position()
  File "/home/paprykarz/.vim/bundle/vdebug/plugin/python/vdebug/event.py", line 25, in by_position
    return event.execute(self.runner)
  File "/home/paprykarz/.vim/bundle/vdebug/plugin/python/vdebug/event.py", line 183, in execute
    char = buf_line[pointer_index]
IndexError: string index out of range
```

I can collapse _$_COOKIE_ line only once,

```
- [Debug] {pon 20 2014 00:38:42} User action in watch window, line 5
```

trying to expand it back gives

```
- [Debug] {pon 20 2014 00:38:45} User action in watch window, line 5

- [Debug] {pon 20 2014 00:38:45} Command: property_get -i 7 -n $_COOKIE -d 0

- [Debug] {pon 20 2014 00:38:45} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="property_get" transaction_id="7" status="break" reason="ok"><error code="300"><message><![CDATA[can not get property]]></message></error></response>

- [ERROR] {pon 20 2014 00:38:45} can not get property
```

It does not matter, whether I try to collapse by pressing Return key or by double clicking on variable line. 

These behaviours occurs also for locals. Please, try multiply expand and collapse several array and object infos. I can provide more informations, if you cannot reproduce this bug.

**Comment by joonty** [comment]
I'm pretty sure this has been fixed, as I can't reproduce it on the `dev` branch. I could be wrong though - and I'd be happy to look into it further if I am!

**Comment by paprykarz** [comment]
The most important bug seems to be fixed: both following multiline elements are displayed correctly after multiple expanding/collapsing the line representing an array, to which they belong.

    <?php

    $f = 1;
    $x= [
        'begin
        end',
    2,3,4,5];

    $a = 1;

    $y=array(
        '<address>Apache/2.4.7 (Debian) Server at kmo.local Port 80</address>
    ',
    2,3,4,5);

    echo 'x'."\n";

Thank you, this was an important bug.

**Comment by padawin** [comment]
Hi, I still have the IndexError, it happened when one of the new line was shorter than the tree level of the variable.

I am about to pull a pull request on this matter.

**Comment by padawin** [comment]
example triggering the error:
<img width="993" alt="screen shot 2017-01-25 at 12 02 29" src="https://cloud.githubusercontent.com/assets/211438/22289968/37af2c30-e2f6-11e6-89b4-616a2ac7c3dc.png">

**Comment by padawin** [comment]
The pull request is: https://github.com/joonty/vdebug/pull/264

**Comment by padawin** [comment]
Also, the tree was broken if the value was multiline and the character at the position pointer_index was not a space.
So I indented all the subsequent lines of the value, wrapped in single quotes, and \n replaced by the "\n" string.

Please let me know your thoughts.

**Comment by padawin** [comment]
To test the second behaviour, set a multiline value with a longish string and open and close repetitively its part of tree:
<img width="940" alt="screen shot 2017-01-25 at 13 58 20" src="https://cloud.githubusercontent.com/assets/211438/22293139/5c6ce110-e306-11e6-98a5-4256aa64082e.png">

This is after having opened and closed it multiple times.

The second commit of the pull request fixes that.

**Comment by BlackIkeEagle** [comment]
Will be fixed in v2, @padawin if you could retest with v2-integration branch?

**Comment by padawin** [comment]
Hi, just got time to test it. It went well, attached a view of a multiline array element collapsed and expanded:
![screenshot from 2017-05-22 17-18-27](https://cloud.githubusercontent.com/assets/211438/26318417/ef730ab2-3f12-11e7-95ce-b0ce09a07501.png)
![screenshot from 2017-05-22 17-18-42](https://cloud.githubusercontent.com/assets/211438/26318418/ef75f682-3f12-11e7-8a6a-63c067942896.png)

**Comment by baroobob** [comment]
Occasionally I have trouble expanding and collapsing variables in the watch window as shown in the screenshot. I'm running Vdebug 1.5.1 in neovim 0.2.2 on an Ubuntu 16.04 Magento server that I ssh into from my macbook. Is it worth trying the issue-312... branch?

![screen shot 2018-04-15 at 7 34 48 pm](https://user-images.githubusercontent.com/3643831/38785343-68a00344-40e4-11e8-87e1-1a4be9853f33.png)
